### ISSUE TITLE
Gradle version not found

### ISSUE THREAD

**Issue by Jackman3005** [dam5s/somanyfeeds.kt#1]
I noticed you do not include a gradle wrapper with this project.

A) What is your preference around using gradle wrapper vs not. I generally prefer the wrapper for consistency

B) Since there is no wrapper, what version of gradle have you been using to compile this?

Cheers mate, hope all's been well!

**Comment by dam5s** [comment]
I usually do include a wrapper. Don't know why I didn't here, let me check if I still have this code locally.

**Comment by dam5s** [comment]
Added gradle wrapper

https://github.com/dam5s/somanyfeeds.kt/commit/1499e107fe53c44df0cde198236fbc7e5e3471a8
